variable "resource_group" {}
variable "location" {}
variable "vnetcidr" {}
variable "websubnetcidr" {}
variable "appsubnetcidr" {}
variable "dbsubnetcidr" {}
variable "frontend" {}
variable "backend" {}
variable "public_ip" {}
